Fixed fluentbit check to use getopts

diff --git a/files/scripts/check_fluentbit_health b/files/scripts/check_fluentbit_health
--- a/files/scripts/check_fluentbit_health
+++ b/files/scripts/check_fluentbit_health
@@ -4,14 +4,20 @@
 FLUENTBIT_HOST="localhost"
 FLUENTBIT_PORT="2020"
 
-# Check if custom host and port are provided as parameters
-if [ ! -z "$1" ]; then
-  FLUENTBIT_HOST=$1
-fi
-
-if [ ! -z "$2" ]; then
-  FLUENTBIT_PORT=$2
-fi
+while getopts "H:p:" opt; do
+  case $opt in
+    H)
+      FLUENTBIT_HOST=$OPTARG
+      ;;
+    p)
+      FLUENTBIT_PORT=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
 
 # Fluent Bit health check URL
 FLUENTBIT_HEALTH_URL="http://${FLUENTBIT_HOST}:${FLUENTBIT_PORT}/api/v1/health"
@@ -21,9 +27,9 @@ HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" $FLUENTBIT_HEALTH_URL)
 
 # Check if the status code is 200
 if [ "$HTTP_STATUS" -eq 200 ]; then
-    echo "OK - Fluent Bit is healthy."
+    echo "OK: Fluent Bit is healthy."
     exit 0
 else
-    echo "CRITICAL - Fluent Bit is not healthy. HTTP Status: $HTTP_STATUS"
+    echo "CRITICAL: Fluent Bit is not healthy. HTTP Status: $HTTP_STATUS"
     exit 2
 fi
